### ISSUE TITLE
Gamepad dead zone support

### ISSUE THREAD

**Issue by qubodup** [jazztickets/irrlamb#11]
My Xbox 360 apparently is not perfect. If I use it once, the ball and camera will move forever, after restarts as well.

Please implement a dead zone setting with a bar for setting the read zone radius (with a default setting ideally). Or at least the option to disable the gamepad.

There's info on dead zone implementation at http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html

**Comment by jazztickets** [comment]
For now you can change the deadzone values in ~/.local/share/irrlamb/[gamepad_name_here].xml

**Comment by qubodup** [comment]
Oh thanks, I should have paid more attention to the release notes!

Please close if you don't plan to put these configs into the GUI.

**Comment by jazztickets** [comment]
No prob. I'll probably just put in a little text box in the options where you can change the deadzone across the board for gamepads. Another person had a similar problem so it definitely needs to be there.

Doing the radial deadzone would be too much work right now since i'd have to completely change how the joystick input works. Maybe in the distant future though.

**Comment by jazztickets** [comment]
Added basic deadzone in d4d35117059c5fe8b072db44a84a81937268f030
